language: ruby
rbenv:
- 2.5.3
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: LApBb4ENmBTshXUtPNcFTOiwFNBC5gvCan5Bwg3fFdZdoDrgRYMHgylaIwkPDZt9GPF/8rTyi922n/rgEhQ5QIVIAfEFXfNAxqvnWYptIm8JV4+Sg+5yDtZBYv5qVP7nukVubdNND2zXloBYX9V1VEUXeNyE5L0ijZqJU4fQ8JEZyptXT5vLGc78esYAl0nxO5t31lNS4xlIloBd+zcLzifRb2I/ypOYFdthBmtQ82bMpOqMCmk9nZaT1mYOKlnkITmdg4vv7K3gpZ9hu2pRTWTzbkxYi2PcxRJzj3BKOaipBFBRX5jU5QSSkGRCCvi2F/HpC8C4rE838kfRMMfL0oKgSvdx/Xpic4kZ+7H+JA6xSkZAFPLP9y0DherIy+efEJtMBGN8BgbFZV+wPC4C0u6lW7/TJij3ygih9JaENfnia94Dc0323seE1j1sThLxRj98rIaQrM++cal61ba0xJvX+iJP1q02TSxr4Gfgt20rAkf/rBdmQpOzqfj+NUZAEvtUIYwkikWggMkdv6VxiPApM5WB1aJoc4okjL6xH2w77bAwHOkP9pIWMUxXV8Qdu4sBqnRfbj2uRppuMGNzrcjoKAXlJI0T+6ZaxeziySmLzi7VXk42Ud4itQFOli/4/xeyK8xjqhMMagZh0Vo2QMTmg5nfgXKrbcS0kIaWmY4=
  app: y
  on:
    repo: nicorithner/destination-planner
    branch: main
